EXE = heapv3.exe
LIB = 

INCLUDE_DIRS = \
    $(ROOT)/code/platform/common/inc \
    $(ROOT)/code/platform/arch/x86/simulator/inc \
    $(ROOT)/code/platform/device/inc \
    $(ROOT)/code/platform/timer/v3/inc \
    $(ROOT)/code/platform/task/common/inc \
    $(ROOT)/code/platform/task/v3/inc \
    $(ROOT)/code/platform/sync/v3/inc \
    $(ROOT)/code/platform/memory/v3/inc \

LINK_LIBS = memoryv3 board ctrlc taskv1 timerv3 device cpu syncv3 common

include $(BUILD)/c.rule
