EXE = 
LIB = libsyncv2.a

INCLUDE_DIRS = \
    $(ROOT)/code/platform/common/inc \
    $(ROOT)/code/platform/arch/x86/simulator/inc \
    $(ROOT)/code/platform/timer/v3/inc \
    $(ROOT)/code/platform/task/common/inc \
    $(ROOT)/code/platform/task/v3/inc \
    $(ROOT)/code/platform/sync/common/inc \
    $(ROOT)/code/platform/sync/v2/inc \
    $(ROOT)/code/platform/device/inc \

LINK_LIBS = 

include $(BUILD)/c.rule
