EXE = 
LIB = libtimerv4.a

INCLUDE_DIRS = \
    $(ROOT)/code/platform/common/inc \
    $(ROOT)/code/platform/arch/x86/simulator/inc \
    $(ROOT)/code/platform/timer/common/inc \
    $(ROOT)/code/platform/timer/v4/inc \
    $(ROOT)/code/platform/device/inc \
    $(ROOT)/code/platform/task/v3/inc \
    $(ROOT)/code/platform/sync/v3/inc \

LINK_LIBS = 

include $(BUILD)/c.rule
