EXE = taskv1.exe
LIB = 

INCLUDE_DIRS = \
    $(ROOT)/code/platform/common/inc \
    $(ROOT)/code/platform/arch/x86/simulator/inc \
    $(ROOT)/code/platform/device/inc \
    $(ROOT)/code/platform/timer/v4/inc \
    $(ROOT)/code/platform/task/common/inc \
    $(ROOT)/code/platform/task/v1/inc \
    $(ROOT)/code/platform/sync/v1/inc \

LINK_LIBS = taskv1 timerv4 device board ctrlc cpu syncv3 common

include $(BUILD)/c.rule
