EXE = 
LIB = libsyncv1.a

INCLUDE_DIRS = \
    $(ROOT)/code/platform/common/inc \
    $(ROOT)/code/platform/arch/x86/simulator/inc \
    $(ROOT)/code/platform/timer/v3/inc \
    $(ROOT)/code/platform/task/common/inc \
    $(ROOT)/code/platform/task/v3/inc \
    $(ROOT)/code/platform/sync/common/inc \
    $(ROOT)/code/platform/sync/v1/inc \
    $(ROOT)/code/platform/device/inc \

LINK_LIBS = 

include $(BUILD)/c.rule
