EXE = 
LIB = libtaskv3.a

INCLUDE_DIRS = \
    $(ROOT)/code/platform/common/inc \
    $(ROOT)/code/platform/arch/x86/simulator/inc \
    $(ROOT)/code/platform/timer/v3/inc \
    $(ROOT)/code/platform/task/common/inc \
    $(ROOT)/code/platform/sync/v3/inc \
    $(ROOT)/code/platform/task/v3/inc \
    $(ROOT)/code/platform/semaphore/inc \
    $(ROOT)/code/platform/device/inc \
    $(ROOT)/code/platform/sync/v3/inc \

LINK_LIBS = 

include $(BUILD)/c.rule
