EXE = 
LIB = lib39vf040.a

INCLUDE_DIRS = \
    $(ROOT)/code/platform/common/inc \
    $(ROOT)/code/platform/arch/x86/simulator/inc \
    $(ROOT)/code/platform/device/inc \
    $(ROOT)/code/platform/task/v3/inc \
    $(ROOT)/code/platform/timer/v4/inc \
    $(ROOT)/code/platform/sync/v3/inc \
    $(ROOT)/code/platform/driver/flash/share/inc \
    $(ROOT)/code/platform/driver/flash/39vf040/inc \

LINK_LIBS = 

include $(BUILD)/c.rule
